/*
 * MyAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.72
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import Establishment from '../model/Establishment';

/**
* Establishments service.
* @module api/EstablishmentsApi
* @version v1
*/
export default class EstablishmentsApi {

    /**
    * Constructs a new EstablishmentsApi. 
    * @alias module:api/EstablishmentsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiEstablishmentsGet operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Establishment>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/EstablishmentsApi~apiEstablishmentsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Establishment];

      return this.apiClient.callApi(
        '/api/Establishments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsIdDelete operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiEstablishmentsIdDelete(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiEstablishmentsIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/Establishments/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsIdGet operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Establishment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsIdGet(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiEstablishmentsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Establishment;

      return this.apiClient.callApi(
        '/api/Establishments/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsIdPut operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {module:model/Establishment} opts.body 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiEstablishmentsIdPut(id, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiEstablishmentsIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/Establishments/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsNameNameGet operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsNameNameGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Establishment>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} name 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsNameNameGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsNameNameGet(name, callback) {
      
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling apiEstablishmentsNameNameGet");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Establishment];

      return this.apiClient.callApi(
        '/api/Establishments/name/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsOpenOpenGet operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsOpenOpenGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Establishment>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Boolean} open 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsOpenOpenGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsOpenOpenGet(open, callback) {
      
      let postBody = null;
      // verify the required parameter 'open' is set
      if (open === undefined || open === null) {
        throw new Error("Missing the required parameter 'open' when calling apiEstablishmentsOpenOpenGet");
      }

      let pathParams = {
        'open': open
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Establishment];

      return this.apiClient.callApi(
        '/api/Establishments/open/{open}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsPost operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Establishment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/Establishment} opts.body 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Establishment;

      return this.apiClient.callApi(
        '/api/Establishments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsScoreRangeGet operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsScoreRangeGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Establishment>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} opts.minScore 
     * @param {Number} opts.maxScore 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsScoreRangeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsScoreRangeGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'minScore': opts['minScore'],'maxScore': opts['maxScore']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Establishment];

      return this.apiClient.callApi(
        '/api/Establishments/score-range', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiEstablishmentsScoreScoreGet operation.
     * @callback moduleapi/EstablishmentsApi~apiEstablishmentsScoreScoreGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Establishment>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} score 
     * @param {module:api/EstablishmentsApi~apiEstablishmentsScoreScoreGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    apiEstablishmentsScoreScoreGet(score, callback) {
      
      let postBody = null;
      // verify the required parameter 'score' is set
      if (score === undefined || score === null) {
        throw new Error("Missing the required parameter 'score' when calling apiEstablishmentsScoreScoreGet");
      }

      let pathParams = {
        'score': score
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Establishment];

      return this.apiClient.callApi(
        '/api/Establishments/score/{score}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}