/*
 * MyAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.72
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Establishment model module.
 * @module model/Establishment
 * @version v1
 */
export default class Establishment {
  /**
   * Constructs a new <code>Establishment</code>.
   * @alias module:model/Establishment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Establishment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Establishment} obj Optional instance to populate.
   * @return {module:model/Establishment} The populated <code>Establishment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Establishment();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('creationDate'))
        obj.creationDate = ApiClient.convertToType(data['creationDate'], 'Date');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('isOpen'))
        obj.isOpen = ApiClient.convertToType(data['isOpen'], 'Boolean');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Establishment.prototype.id = undefined;

/**
 * @member {String} name
 */
Establishment.prototype.name = undefined;

/**
 * @member {Date} creationDate
 */
Establishment.prototype.creationDate = undefined;

/**
 * @member {String} location
 */
Establishment.prototype.location = undefined;

/**
 * @member {Boolean} isOpen
 */
Establishment.prototype.isOpen = undefined;

/**
 * @member {Number} score
 */
Establishment.prototype.score = undefined;

