/*
 * MyAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.72
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Product model module.
 * @module model/Product
 * @version v1
 */
export default class Product {
  /**
   * Constructs a new <code>Product</code>.
   * @alias module:model/Product
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('publicationId'))
        obj.publicationId = ApiClient.convertToType(data['publicationId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Product.prototype.id = undefined;

/**
 * @member {String} name
 */
Product.prototype.name = undefined;

/**
 * @member {Date} _date
 */
Product.prototype._date = undefined;

/**
 * @member {Number} price
 */
Product.prototype.price = undefined;

/**
 * @member {Number} score
 */
Product.prototype.score = undefined;

/**
 * @member {String} publicationId
 */
Product.prototype.publicationId = undefined;

