/*
 * MyAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.72
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Establishment from './Establishment';
import Product from './Product';

/**
 * The Publication model module.
 * @module model/Publication
 * @version v1
 */
export default class Publication {
  /**
   * Constructs a new <code>Publication</code>.
   * @alias module:model/Publication
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Publication</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Publication} obj Optional instance to populate.
   * @return {module:model/Publication} The populated <code>Publication</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Publication();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('totalPrice'))
        obj.totalPrice = ApiClient.convertToType(data['totalPrice'], 'Number');
      if (data.hasOwnProperty('totalScore'))
        obj.totalScore = ApiClient.convertToType(data['totalScore'], 'Number');
      if (data.hasOwnProperty('photo'))
        obj.photo = ApiClient.convertToType(data['photo'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('establishmentId'))
        obj.establishmentId = ApiClient.convertToType(data['establishmentId'], 'String');
      if (data.hasOwnProperty('establishment'))
        obj.establishment = Establishment.constructFromObject(data['establishment']);
      if (data.hasOwnProperty('products'))
        obj.products = ApiClient.convertToType(data['products'], [Product]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Publication.prototype.id = undefined;

/**
 * @member {Date} _date
 */
Publication.prototype._date = undefined;

/**
 * @member {Number} totalPrice
 */
Publication.prototype.totalPrice = undefined;

/**
 * @member {Number} totalScore
 */
Publication.prototype.totalScore = undefined;

/**
 * @member {String} photo
 */
Publication.prototype.photo = undefined;

/**
 * @member {String} userId
 */
Publication.prototype.userId = undefined;

/**
 * @member {String} establishmentId
 */
Publication.prototype.establishmentId = undefined;

/**
 * @member {module:model/Establishment} establishment
 */
Publication.prototype.establishment = undefined;

/**
 * @member {Array.<module:model/Product>} products
 */
Publication.prototype.products = undefined;

