/*
 * MyAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.72
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version v1
 */
export default class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('surname'))
        obj.surname = ApiClient.convertToType(data['surname'], 'String');
      if (data.hasOwnProperty('birthDate'))
        obj.birthDate = ApiClient.convertToType(data['birthDate'], 'Date');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('creationDate'))
        obj.creationDate = ApiClient.convertToType(data['creationDate'], 'Date');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
      if (data.hasOwnProperty('moneySpent'))
        obj.moneySpent = ApiClient.convertToType(data['moneySpent'], 'Number');
      if (data.hasOwnProperty('publicationsNumber'))
        obj.publicationsNumber = ApiClient.convertToType(data['publicationsNumber'], 'Number');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
User.prototype.id = undefined;

/**
 * @member {String} username
 */
User.prototype.username = undefined;

/**
 * @member {String} name
 */
User.prototype.name = undefined;

/**
 * @member {String} surname
 */
User.prototype.surname = undefined;

/**
 * @member {Date} birthDate
 */
User.prototype.birthDate = undefined;

/**
 * @member {String} email
 */
User.prototype.email = undefined;

/**
 * @member {String} password
 */
User.prototype.password = undefined;

/**
 * @member {Date} creationDate
 */
User.prototype.creationDate = undefined;

/**
 * @member {Boolean} active
 */
User.prototype.active = undefined;

/**
 * @member {Number} moneySpent
 */
User.prototype.moneySpent = undefined;

/**
 * @member {Number} publicationsNumber
 */
User.prototype.publicationsNumber = undefined;

/**
 * @member {String} role
 */
User.prototype.role = undefined;

