/*
 * MyAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.72
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import ErrorResponse from './model/ErrorResponse';
import Establishment from './model/Establishment';
import LoginRequest from './model/LoginRequest';
import LoginResponse from './model/LoginResponse';
import Product from './model/Product';
import Publication from './model/Publication';
import User from './model/User';
import EstablishmentsApi from './api/EstablishmentsApi';
import LoginApi from './api/LoginApi';
import ProductsApi from './api/ProductsApi';
import PublicationsApi from './api/PublicationsApi';
import UsersApi from './api/UsersApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MyApi = require('index'); // See note below*.
* var xxxSvc = new MyApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MyApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MyApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MyApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The Establishment model constructor.
     * @property {module:model/Establishment}
     */
    Establishment,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginResponse model constructor.
     * @property {module:model/LoginResponse}
     */
    LoginResponse,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The Publication model constructor.
     * @property {module:model/Publication}
     */
    Publication,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The EstablishmentsApi service constructor.
    * @property {module:api/EstablishmentsApi}
    */
    EstablishmentsApi,

    /**
    * The LoginApi service constructor.
    * @property {module:api/LoginApi}
    */
    LoginApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:api/ProductsApi}
    */
    ProductsApi,

    /**
    * The PublicationsApi service constructor.
    * @property {module:api/PublicationsApi}
    */
    PublicationsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
